apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://runatlantis.github.io/helm-charts
    chart: atlantis
    targetRevision: 4.11.2
    helm:
      values: |-
        statefulSet:
          annotations:
            secret.reloader.stakater.com/reload: "atlantis-secrets"
        atlantisUrl: http://atlantis-development-cluster.projekte.eitco.de
        orgAllowlist: gitea-development-cluster.projekte.eitco.de/gitea_admin/*
        hidePrevPlanComments: true
        serviceAccount:
          create: false
          mount: true
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 512Mi
        ingress:
          enabled: true
          annotations:
            # cert-manager.io/cluster-issuer: "letsencrypt-prod"
            traefik.ingress.kubernetes.io/router.entrypoints: web
          path: /
          host: atlantis-development-cluster.projekte.eitco.de
          ingressClassName: "traefik"
          tls:
            - secretName: atlantis-tls
              hosts:
                - atlantis-development-cluster.projekte.eitco.de
        loadEnvFromSecrets:
          - atlantis-secrets
        repoConfig: |
          ---
          repos:
          - id: gitea-development-cluster.projekte.eitco.de/gitea_admin/*
            workflow: default
            allowed_overrides: [apply_requirements]
            apply_requirements: [mergeable]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2