apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: http://gitea-development-cluster.projekte.eitco.de/gitea_admin/development-gitops.git
    path: registry/development-cluster/components/reloader
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true